SET foreign_key_checks = 0;

-- DROP ALL TABLES
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS Post;
DROP TABLE IF EXISTS Comments;
DROP TABLE IF EXISTS Likes;
DROP TABLE IF EXISTS UserArchives;
DROP TABLE IF EXISTS PostArchives;

-- TABLES    

-- USER TABLE
CREATE TABLE User (
    uid INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- CATEGORY TABLE
CREATE TABLE Category (
    cid INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

-- POST TABLE
CREATE TABLE Post (
    pid INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    uid INT UNSIGNED NOT NULL,
    cid INT UNSIGNED NOT NULL,
    title VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (uid) REFERENCES User(uid) ON DELETE CASCADE,
    FOREIGN KEY (cid) REFERENCES Category(cid)
);

-- COMMENTS TABLE
CREATE TABLE Comments (
    commentID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    uid INT UNSIGNED NOT NULL,
    pid INT UNSIGNED NOT NULL,
    comment TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (uid) REFERENCES User(uid) ON DELETE CASCADE,
    FOREIGN KEY (pid) REFERENCES Post(pid) ON DELETE CASCADE
);

-- LIKES TABLE
CREATE TABLE Likes (
    uid INT UNSIGNED NOT NULL,
    pid INT UNSIGNED NOT NULL,
    PRIMARY KEY (uid, pid),
    FOREIGN KEY (uid) REFERENCES User(uid) ON DELETE CASCADE,
    FOREIGN KEY (pid) REFERENCES Post(pid) ON DELETE CASCADE
);

-- USER ARCHIVES TABLE
CREATE TABLE UserArchives (
    uid INT UNSIGNED NOT NULL PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- POST ARCHIVES TABLE
CREATE TABLE PostArchives LIKE Post;

-- Enable foreign key checks again
SET foreign_key_checks = 1;